---
title: "R Notebook"
output: html_notebook
---


```{r}
setwd("./")
getwd()
load("../DATA/pchic.RData")

Cpgs_mapinfo <- read.csv("../DATA/CpGs_mapinfo.csv")
```

```{r}
library(GenomicRanges)


chromatine_Ranges <- GRanges(
  seqnames = pchic$baitChr,
  ranges = IRanges(start = pchic$baitStart, end = pchic$baitEnd),
  baitName = pchic$baitName,
  oeStart = pchic$oeStart,
  oeEnd = pchic$oeEnd,
  oeName = pchic$oeName
)
chromatine_Ranges

CpGs_Ranges <- GRanges(
  seqnames = Cpgs_mapinfo$CHR,
  ranges = IRanges(start = Cpgs_mapinfo$MAPINFO, end = Cpgs_mapinfo$MAPINFO+1)
)

CpGs_Ranges
```

```{r}
CpGs_chromatine_Ranges <- subsetByOverlaps(chromatine_Ranges ,CpGs_Ranges)
CpGs_chromatine_Ranges
```

```{r}
library(igraph)
library(readr)
library(dplyr)

CpGs_chromatine_Network <- mcols(CpGs_chromatine_Ranges)[,c(1,4)]
CpGs_chromatine_Network <- CpGs_chromatine_Network[which(CpGs_chromatine_Network$oeName != "."),]
CpGs_chromatine_Network

CpGs_chromatine_graph <- graph_from_data_frame(CpGs_chromatine_Network, directed = F)
CpGs_chromatine_graph
tkplot(CpGs_chromatine_graph)

write.csv(CpGs_chromatine_Network, file = "../Results/CpGs_chromatine_Network.csv", row.names = FALSE)
```

